# -*- coding: utf-8 -*-
"""ubah order pdf ke excel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RZhRTTT3AkYXWOSFP4Xmp2YEgIbSFjLt
"""

!pip install pandas openpyxl

import pandas as pd
from openpyxl import Workbook

# Data yang diekstrak dari PDF
data = {
    "Order Number": ["#1634"],
    "Customer Name": ["Destri Wardhani"],
    "Email": ["destri_kusuma@yahoo.com"],
    "Phone": ["+62 856-1342-999"],
    "Shipping Address": ["Jl. Zeni AD I No. 1 RT006/03, Rawa Jati, Pancoran, Jakarta Selatan, JK 12750, Indonesia"],
    "Billing Address": ["Same as shipping address"],
    "Product Name": ["Bamboo Spice Apron - SALE", "Bamboo Spice Oven Mitt - SALE"],
    "Category": ["HOMEWARES", "HOMEWARES"],
    "SKU": ["CK04BBS", "CK06BBS"],
    "Quantity": [1, 1],
    "Price": [120000, 78000],
    "Subtotal": [198000],
    "Shipping Cost": [35000],
    "Total": [233000],
    "Payment Method": ["DOKU Payment"],
    "Payment Status": ["Paid"]
}

# Get the length of the product lists
num_products = len(data["Product Name"])

# Duplicate single-value lists to match the number of products
data["Order Number"] = data["Order Number"] * num_products
data["Customer Name"] = data["Customer Name"] * num_products
data["Email"] = data["Email"] * num_products
data["Phone"] = data["Phone"] * num_products
data["Shipping Address"] = data["Shipping Address"] * num_products
data["Billing Address"] = data["Billing Address"] * num_products
data["Subtotal"] = data["Subtotal"] * num_products
data["Shipping Cost"] = data["Shipping Cost"] * num_products
data["Total"] = data["Total"] * num_products
data["Payment Method"] = data["Payment Method"] * num_products
data["Payment Status"] = data["Payment Status"] * num_products

# Membuat DataFrame
order_df = pd.DataFrame(data)

# Menyimpan ke file Excel
excel_path = "/content/order_details.xlsx"
order_df.to_excel(excel_path, index=False)

print(f"File Excel telah disimpan di: {excel_path}")